
services:
  app:
    build: .
    ports:
        - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/quizroom
      DB_USERNAME: quizuser
      DB_PASSWORD: quizPass
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
    depends_on:
      - db
      - cache

  db:
    image: postgres:16.11-alpine3.23
    environment:
      POSTGRES_DB: quizroom
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizPass
    ports:
      - "5432:5432"

  cache:
    image: redis:8.4.0
    ports:
      - "6379:6379"
